"""tokens, delete

Revision ID: c3fa6905edb6
Revises: 3dc232bbd949
Create Date: 2024-08-20 10:57:26.137449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3fa6905edb6'
down_revision = '3dc232bbd949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint('followers_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('followers_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['followed_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('message_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('message_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['recipient_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('notification_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('token_expiration', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_column('token_expiration')
        batch_op.drop_column('token')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_ibfk_1', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notification_ibfk_1', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('message_ibfk_1', 'user', ['recipient_id'], ['id'])
        batch_op.create_foreign_key('message_ibfk_2', 'user', ['sender_id'], ['id'])

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('followers_ibfk_2', 'user', ['follower_id'], ['id'])
        batch_op.create_foreign_key('followers_ibfk_1', 'user', ['followed_id'], ['id'])

    # ### end Alembic commands ###
